-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.image
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_at timestamp(6) with time zone DEFAULT now(),
    gallery_id integer NOT NULL,
    image text COLLATE pg_catalog."default" NOT NULL,
    thumbnail_image text COLLATE pg_catalog."default",
    CONSTRAINT image_pkey PRIMARY KEY (id),
    CONSTRAINT image_gallery_id_fkey FOREIGN KEY (gallery_id)
        REFERENCES public.gallery (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.image
    OWNER to postgres;

ALTER TABLE IF EXISTS public.image
    ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_image
    ON public.image USING btree
    (id ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public._prisma_migrations
(
    id character varying(36) COLLATE pg_catalog."default" NOT NULL,
    checksum character varying(64) COLLATE pg_catalog."default" NOT NULL,
    finished_at timestamp with time zone,
    migration_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    logs text COLLATE pg_catalog."default",
    rolled_back_at timestamp with time zone,
    started_at timestamp with time zone NOT NULL DEFAULT now(),
    applied_steps_count integer NOT NULL DEFAULT 0,
    CONSTRAINT _prisma_migrations_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public._prisma_migrations
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public.gallery
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_at timestamp(6) with time zone DEFAULT now(),
    name text COLLATE pg_catalog."default" NOT NULL,
    cover_photo text COLLATE pg_catalog."default",
    category text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT gallery_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.gallery
    OWNER to postgres;

ALTER TABLE IF EXISTS public.gallery
    ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_gallery
    ON public.gallery USING btree
    (id ASC NULLS LAST)
    TABLESPACE pg_default;
